version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: 16.18.0
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Install server dependencies
          command: npm run install:server
      - run:
          name: Build server
          command: npm run build:server
      - run:
          name: Build website
          command: npm run build:website
      - run:
          name: Deploy server to Elastic Beanstalk
          command: npm run deploy:server
      - run:
          name: Deploy website to AWS S3
          command: npm run deploy:website
